# Generated by Django 5.0.6 on 2024-11-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('nome_paciente', models.CharField(default='', max_length=150)),
                ('nome_medico', models.CharField(default='', max_length=150)),
                ('crm', models.CharField(default='', max_length=20)),
                ('data', models.DateField(blank=True, default=None, null=True)),
                ('medicamentos_prescritos', models.CharField(default='', max_length=500)),
                ('dosagem', models.CharField(default='', max_length=300)),
            ],
        ),
    ]
