# Generated by Django 5.1.3 on 2024-11-07 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('nome', models.CharField(default='', max_length=150)),
                ('cpf', models.CharField(default='', max_length=14)),
                ('telefone', models.CharField(default='', max_length=15)),
                ('email', models.EmailField(default='', max_length=254)),
                ('cep', models.CharField(default='', max_length=9)),
                ('logradouro', models.CharField(default='', max_length=150)),
                ('numero', models.CharField(default='', max_length=10)),
                ('complemento', models.CharField(default='', max_length=150)),
                ('bairro', models.CharField(default='', max_length=100)),
                ('cidade', models.CharField(default='', max_length=100)),
                ('uf', models.CharField(default='', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('nome', models.CharField(default='', max_length=150)),
                ('cnpj', models.CharField(default='', max_length=18)),
                ('telefone', models.CharField(default='', max_length=15)),
                ('email', models.EmailField(default='', max_length=254)),
                ('cep', models.CharField(default='', max_length=9)),
                ('logradouro', models.CharField(default='', max_length=150)),
                ('numero', models.CharField(default='', max_length=10)),
                ('complemento', models.CharField(default='', max_length=150)),
                ('bairro', models.CharField(default='', max_length=100)),
                ('cidade', models.CharField(default='', max_length=100)),
                ('uf', models.CharField(default='', max_length=2)),
                ('desconto', models.FloatField(default=0.0)),
                ('data_validade', models.DateField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('nome', models.CharField(default='', max_length=150)),
                ('cnpj', models.CharField(default='', max_length=18)),
                ('telefone', models.CharField(default='', max_length=15)),
                ('email', models.EmailField(default='', max_length=254)),
                ('cep', models.CharField(default='', max_length=9)),
                ('logradouro', models.CharField(default='', max_length=150)),
                ('numero', models.CharField(default='', max_length=10)),
                ('complemento', models.CharField(default='', max_length=150)),
                ('bairro', models.CharField(default='', max_length=100)),
                ('cidade', models.CharField(default='', max_length=100)),
                ('uf', models.CharField(default='', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('nome', models.CharField(default='', max_length=150)),
                ('cpf', models.CharField(default='', max_length=14)),
                ('telefone', models.CharField(default='', max_length=15)),
                ('email', models.EmailField(default='', max_length=254)),
                ('cep', models.CharField(default='', max_length=9)),
                ('logradouro', models.CharField(default='', max_length=150)),
                ('numero', models.CharField(default='', max_length=10)),
                ('complemento', models.CharField(default='', max_length=150)),
                ('bairro', models.CharField(default='', max_length=100)),
                ('cidade', models.CharField(default='', max_length=100)),
                ('uf', models.CharField(default='', max_length=2)),
                ('cargo', models.CharField(default='', max_length=150)),
                ('salario', models.FloatField(default=0.0)),
                ('data_admissao', models.DateField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('nome', models.CharField(default='', max_length=150)),
                ('descricao', models.CharField(default='', max_length=500)),
                ('preco', models.FloatField(default=0.0)),
                ('categoria', models.CharField(default='', max_length=150)),
                ('quantidade', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('nome_paciente', models.CharField(default='', max_length=150)),
                ('nome_medico', models.CharField(default='', max_length=150)),
                ('crm', models.CharField(default='', max_length=20)),
                ('data', models.DateField(blank=True, default=None, null=True)),
                ('medicamentos_prescritos', models.CharField(default='', max_length=500)),
                ('dosagem', models.CharField(default='', max_length=300)),
            ],
        ),
    ]
