# Generated by Django 5.1.3 on 2024-11-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='id',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(default='', max_length=150, primary_key=True, serialize=False),
        ),
    ]
