# Generated by Django 5.1.3 on 2024-11-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0002_remove_cliente_id_alter_cliente_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
