# Generated by Django 5.0.6 on 2024-11-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('nome', models.CharField(default='', max_length=150)),
                ('descricao', models.CharField(default='', max_length=500)),
                ('preco', models.FloatField(default=0.0)),
                ('categoria', models.CharField(default='', max_length=150)),
                ('quantidade', models.IntegerField(default=0)),
            ],
        ),
    ]
